{{- if not .Values.postgres.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "aria-gatekeeper.fullname" . }}-secrets
  labels:
    app.kubernetes.io/name: aria-gatekeeper
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
data:
  {{- if .Values.redis.password }}
  redis-password: {{ .Values.redis.password | b64enc | quote }}
  {{- end }}
  {{- if .Values.postgres.password }}
  postgres-password: {{ .Values.postgres.password | b64enc | quote }}
  {{- end }}
{{- end }}
